### Given a string s consisting of lowercase English Letters. Return the first non-repeating character in s.
def non_repeating(s):
    count=[0]*26
    for i in s:
        count[ord(i)-ord('a')]+=1
    for i in s:
        if count[ord(i)-ord('a')]==1:
            return i
    return -1
def non(s):
    count={}
    for i in s:
        if i in count:
            count[i]+=1
        else:
            count[i]=1
    for i in s:
        if count[i]==1:
            return i
    return -1
# Example usage  ## driver code is generated by the AI, and it is not part of the original code.

if __name__ == "__main__":
    s = "leetcode"
    print(non_repeating(s))  # Output: 'l'
    print(non(s))  # Output: 'l'

    s = "loveleetcode"
    print(non_repeating(s))  # Output: 'v'
    print(non(s))  # Output: 'v'

    s = "aabb"
    print(non_repeating(s))  # Output: -1
    print(non(s))  # Output: -1