###Given an array of n names arr of candidates in an election, where each name is a string of lowercase characters.
# A candidate name in the array represents a vote casted to the candidate.
# Print the name of the candidate that received the maximum count of votes.
# If there is a draw between two candidates, then print lexicographically smaller name.
def winner(arr,n):
    count={}
    for i in arr:
        if i in count:
            count[i]+=1
        else:
            count[i]=1
    max_count = 0
    winner_name = ""
    for name, votes in count.items():
        if votes>max_count or (votes == max_count and len(name) < len(winner_name)):
            max_count = votes
            winner_name = name
    return winner_name
# Example usage## driver code is generated by the AI, and it is not part of the original code.

if __name__ == "__main__":
    arr = ["alice", "bob", "alice", "charlie", "bob", "alice"]
    n = len(arr)
    print(winner(arr, n))  # Output: 'alice'

    arr = ["john", "doe", "john", "jane", "doe"]
    n = len(arr)
    print(winner(arr, n))  # Output: 'doe'

    arr = ["a", "b", "c", "a", "b"]
    n = len(arr)
    print(winner(arr, n))  # Output: 'a'
