##Given an array arr[], find the first repeating element.
# The element should occur more than once and the index of its first occurrence should be the smallest.
def first(arr):
    count = {}
    for i in arr:
        if i in count:
            count[i] += 1
        else:
            count[i] = 1
    for i in count:
        if count[i]>1:
            return i
    return -1
# Example usage ## driver code is generated by the AI, and it is not part of the original code.
if __name__ == "__main__":
    arr = [1, 2, 3, 2, 1]
    print(first(arr))  # Output: 1

    arr = [4, 5, 6, 7, 8, 4]
    print(first(arr))  # Output: 4

    arr = [9, 10, 11]
    print(first(arr))  # Output: -1
