## You are given an array of integers arr[]. You need to print the count of non-repeated elements in the array.
def count_non(arr):
    count=0
    nums={}
    for i in arr:
        if i in nums:
            nums[i]+=1
        else:
            nums[i]=1
    for i in nums:
        if nums[i]==1:
            count+=1
    return count
# Example usage ## driver code is generated by the AI, and it is not part of the original code.
if __name__ == "__main__":
    arr = [1, 2, 3, 2, 1]
    print(count_non(arr))  # Output: 1 (only 3 is non-repeated)

    arr = [4, 5, 6, 7, 8, 4]
    print(count_non(arr))  # Output: 4 (5, 6, 7, and 8 are non-repeated)

    arr = [9, 10, 11]
    print(count_non(arr))  # Output: 3 (all are non-repeated)
    
