### two sum problem
def two(arr,target):
    count={}
    for i in range(len(arr)):
        complement = target - arr[i]
        if complement in count:
            return [count[complement], i]
        count[arr[i]] = i
    return []
# Example usage ## driver code is generated by the AI, and it is not part of the original code.
if __name__ == "__main__":
    arr = [2, 7, 11, 15]
    target = 9
    print(two(arr, target))  # Output: [0, 1] (2 + 7 = 9)

    arr = [3, 2, 4]
    target = 6
    print(two(arr, target))  # Output: [1, 2] (2 + 4 = 6)

    arr = [3, 3]
    target = 6
    print(two(arr, target))  # Output: [0, 1] (3 + 3 = 6)
