##Given an array arr[] where no two adjacent elements are same, find the index of a peak element.
# An element is considered to be a peak if it is greater than its adjacent elements (if they exist).
# If there are multiple peak elements, return index of any one of them.
# The output will be peak element if the index returned by your function is correct.
def peak_element(arr):
    n=len(arr)
    left,right=0,n-1
    while left<right:
        mid=(left+right)//2
        if arr[mid]<arr[mid+1]:
            left=mid+1
        else:
            right=mid
    return left
# Example usage: ## driver code is generated by the AI
if __name__ == "__main__":
    arr = [1, 3, 20, 4, 1, 0]
    index = peak_element(arr)
    if index != -1:
        print(f"Peak element found at index: {index}")
    else:
        print("No peak element found")


