## find the first and last index of a given element in a sorted array
## time complexity: O(log n)
def search(arr,target):
    left,right=0,len(arr)-1
    first,last=-1,-1
    while left<right:
        mid=(left+right)//2
        if arr[mid]<target:
            left=mid+1
        elif arr[mid]>target:
            right=mid-1
        else:
            if mid==0 or arr[mid]!=arr[mid-1]:
                first=mid
                break
            else:
                right=mid-1
    left,right=0,len(arr)-1
    while left<right:
        mid=(left+right)//2
        if arr[mid]<target:
            left=mid+1
        elif arr[mid]>target:
          right=mid-1
        else:
            if mid==len(arr)-1 or arr[mid]!=arr[mid+1]:
                last=mid
                break
            else:
                left=mid+1
    return first, last
# Example usage: ## driver code is generated by the AI
if __name__ == "__main__":
    arr = [1, 2, 2, 2, 3, 4, 5]
    target = 2
    first_index, last_index = search(arr, target)
    if first_index != -1 and last_index != -1:
        print(f"First index: {first_index}, Last index: {last_index}")
    else:
        print("Element not found in the array")
